More rework of CI and justfiles (#33)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,16 +16,16 @@ jobs:
     name: Test
     runs-on: ubuntu-latest
     steps:
-      - uses: taiki-e/install-action@v2
-        with: { tool: 'just,cargo-binstall,cargo-llvm-cov' }
       - uses: actions/checkout@v4
       - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
         uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: 'just,cargo-binstall,cargo-llvm-cov' }
       - run: sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config
       - name: Install PGRX with the needed version
         run: cargo binstall cargo-pgrx --version "$(just print-pgrx-version)"
       - run: cargo pgrx init
-      - run: RUST_BACKTRACE=1 just ci-test
+      - run: just ci-test
       - name: Generate code coverage
         run: just ci-coverage
       - name: Upload coverage to Codecov
@@ -57,3 +57,13 @@ jobs:
 #      - uses: actions/checkout@v4
 #      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
 #        uses: Swatinem/rust-cache@v2
+
+  # This job checks if any of the previous jobs failed or were canceled.
+  # This approach also allows some jobs to be skipped if they are not needed.
+  ci-passed:
+    if: always()
+    needs: [ test ]
+    runs-on: ubuntu-latest
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: exit 1
